### ISSUE TITLE
Slider selects text

### ISSUE THREAD

**Issue by christopher-besch** [Octoframes/compare_view#21]
as shown here: https://github.com/kolibril13/jupyter-splitview/pull/24

**Comment by christopher-besch** [comment]
@kolibril13, this seems to be an issue with Jupyter Lab only. This, #19 and #20 seem to only exist in Jupyter Lab. Do you have any explanation for this?

**Comment by kolibril13** [comment]
I've tried it again, but still same issue.
But should the submodule version not be updated in the pull request?
Currently it is 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/44469195/178262088-2127a95c-6461-4582-b52c-057082c66d4a.png">
but there are newer versions available:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/44469195/178262174-abff12fb-6abd-49ec-ac68-fb7fb7b5427b.png">


> @kolibril13, this seems to be an issue with Jupyter Lab only. This, https://github.com/Octoframes/compare_view/issues/19 and https://github.com/Octoframes/compare_view/issues/20 seem to only exist in Jupyter Lab. Do you have any explanation for this?

I've never seen this before, and I don't have an idea what might cause it.

**Comment by christopher-besch** [comment]
Sorry, my bad.

**Comment by kolibril13** [comment]
Just tried again, still same error.

**Comment by christopher-besch** [comment]
Odd, I don't have this issue...
I only tried this on Firefox—what browsers did you test?

EDIT: This is also an issue on Edge.

**Comment by kolibril13** [comment]
I tested it now in the following browsers:
Google Chrome: Bug present
Safari: No bug
Firefox: No bug

Additional note: VS Code Notebook: Widget is not showing at all.

**Comment by christopher-besch** [comment]
I think I solved it; could you try again, please?

**Comment by christopher-besch** [comment]
...

**Comment by christopher-besch** [comment]
Thanks!
