### ISSUE TITLE
New option: hide slider tails

### ISSUE THREAD

**Issue by kolibril13** [Octoframes/compare_view#32]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/44469195/179503181-5e7150ed-bdeb-453e-8781-9b99a4caca63.png">
It could be optional to cut these off.    

Screenshot from jupyter_compare_view.

**Comment by christopher-besch** [comment]
These bits exist because the image has quite a large transparent border. The slider goes from the top of the image to the bottom.
Therefore, I think this should be handled on the Python side of Jupyter compare_view.

**Comment by kolibril13** [comment]
Thanks! It's actually caused by Matplotlib not filling the whole image canvas in imshow. I will update the notebook soon.
