### ISSUE TITLE
Round Mask with Image Divider for > 2 images

### ISSUE THREAD

**Issue by kolibril13** [Octoframes/compare_view#8]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/44469195/178102912-fdadab2c-6870-42ff-969d-2cb73d4e6fa7.png">

**Comment by christopher-besch** [comment]
I don't understand this issue.
What kind of image divider do you mean?

**Comment by christopher-besch** [comment]
Can I close this issue?

**Comment by kolibril13** [comment]
yep!
